import mysql.connector
pas="imaditya@123"#mysql password
mydb=mysql.connector.connect(host="localhost",user="root",passwd=pas)
mycursor=mydb.cursor()
mycursor.execute("create database resturant3")
mycursor.execute("use resturant")
mycursor.execute("create table login_details(Username VARCHAR(20) UNIQUE NOT null, Password Varchar(20) UNIQUE NOT NULL,Designation varchar(20))")
mycursor.execute("insert into login_details values('owner','owner@123','owner')")
mycursor.execute("create table resturant_details(details varchar(30) not null, Value varchar(50) not null)")
mycursor.execute("insert INTO resturant_details VALUES('Phone no','9987 9987')")
mycursor.execute("insert INTO resturant_details VALUES('Address','Block-J, Saket, Khanpur, New Delhi')")
mycursor.execute("insert INTO resturant_details VALUES('email','pizza_lovers@gmail.com')")
mycursor.execute("insert INTO resturant_details VALUES('website','pizzalovers.com')")
mycursor.execute("create table id(item_id int, order_id int, employee_id int)")
mycursor.execute("insert into id values(100,1000,100)")
mycursor.execute("create table employee(employee_id int, first_name varchar(15), last_name varchar(15), gender char(1), DOB date, email varchar(40), phone_no char(10), address varchar(100),dlv_pincode char(9))")
mycursor.execute("create table order_item(order_id int,item_name varchar(25),size varchar(10),price int,qty int)")
mycursor.execute("create table order_detail(order_id int, customer_name varchar(30),customer_phone_no char(10),customer_address varchar(60),pincode char(6),count_items int,amount int,status varchar(20))")
mycursor.execute("create table menu(item_id int,name char(35),S int,M int,L int)")
mydb.commit()
print("Installation Completed")
